# Generated by Django 4.1.1 on 2022-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("texto", models.CharField(max_length=1000)),
                ("articulo_nro", models.IntegerField()),
                ("username_autor", models.CharField(max_length=100)),
                ("fecha_de_publicacion", models.DateField(null=True)),
            ],
            options={
                "verbose_name_plural": "Articulos",
            },
        ),
        migrations.CreateModel(
            name="Autores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.CreateModel(
            name="Secciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "Secciones",
            },
        ),
    ]
