# Generated by Django 4.1.1 on 2022-11-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_remove_secciones_nombre_secciones_categoria_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulos",
            name="imagen_de_portada",
            field=models.ImageField(blank=True, null=True, upload_to="covers"),
        ),
        migrations.AddField(
            model_name="articulos",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
